// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: seeder_factory.proto

package route;

public interface EndpointOrBuilder extends
    // @@protoc_insertion_point(interface_extends:route.Endpoint)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string transport = 1;</code>
   */
  java.lang.String getTransport();
  /**
   * <code>string transport = 1;</code>
   */
  com.google.protobuf.ByteString
      getTransportBytes();

  /**
   * <code>string ip = 2;</code>
   */
  java.lang.String getIp();
  /**
   * <code>string ip = 2;</code>
   */
  com.google.protobuf.ByteString
      getIpBytes();

  /**
   * <code>int32 port = 3;</code>
   */
  int getPort();
}
