// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto/seeder_factory.proto

package route;

/**
 * Protobuf type {@code route.KeywordsMessage}
 */
public  final class KeywordsMessage extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:route.KeywordsMessage)
    KeywordsMessageOrBuilder {
private static final long serialVersionUID = 0L;
  // Use KeywordsMessage.newBuilder() to construct.
  private KeywordsMessage(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private KeywordsMessage() {
    keyword_ = com.google.protobuf.LazyStringArrayList.EMPTY;
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private KeywordsMessage(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();
            if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
              keyword_ = new com.google.protobuf.LazyStringArrayList();
              mutable_bitField0_ |= 0x00000001;
            }
            keyword_.add(s);
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
        keyword_ = keyword_.getUnmodifiableView();
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return route.SeederFactoryProto.internal_static_route_KeywordsMessage_descriptor;
  }

  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return route.SeederFactoryProto.internal_static_route_KeywordsMessage_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            route.KeywordsMessage.class, route.KeywordsMessage.Builder.class);
  }

  public static final int KEYWORD_FIELD_NUMBER = 1;
  private com.google.protobuf.LazyStringList keyword_;
  /**
   * <code>repeated string keyword = 1;</code>
   */
  public com.google.protobuf.ProtocolStringList
      getKeywordList() {
    return keyword_;
  }
  /**
   * <code>repeated string keyword = 1;</code>
   */
  public int getKeywordCount() {
    return keyword_.size();
  }
  /**
   * <code>repeated string keyword = 1;</code>
   */
  public java.lang.String getKeyword(int index) {
    return keyword_.get(index);
  }
  /**
   * <code>repeated string keyword = 1;</code>
   */
  public com.google.protobuf.ByteString
      getKeywordBytes(int index) {
    return keyword_.getByteString(index);
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    for (int i = 0; i < keyword_.size(); i++) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, keyword_.getRaw(i));
    }
    unknownFields.writeTo(output);
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    {
      int dataSize = 0;
      for (int i = 0; i < keyword_.size(); i++) {
        dataSize += computeStringSizeNoTag(keyword_.getRaw(i));
      }
      size += dataSize;
      size += 1 * getKeywordList().size();
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof route.KeywordsMessage)) {
      return super.equals(obj);
    }
    route.KeywordsMessage other = (route.KeywordsMessage) obj;

    boolean result = true;
    result = result && getKeywordList()
        .equals(other.getKeywordList());
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (getKeywordCount() > 0) {
      hash = (37 * hash) + KEYWORD_FIELD_NUMBER;
      hash = (53 * hash) + getKeywordList().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static route.KeywordsMessage parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static route.KeywordsMessage parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static route.KeywordsMessage parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static route.KeywordsMessage parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static route.KeywordsMessage parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static route.KeywordsMessage parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static route.KeywordsMessage parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static route.KeywordsMessage parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static route.KeywordsMessage parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static route.KeywordsMessage parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static route.KeywordsMessage parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static route.KeywordsMessage parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(route.KeywordsMessage prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code route.KeywordsMessage}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:route.KeywordsMessage)
      route.KeywordsMessageOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return route.SeederFactoryProto.internal_static_route_KeywordsMessage_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return route.SeederFactoryProto.internal_static_route_KeywordsMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              route.KeywordsMessage.class, route.KeywordsMessage.Builder.class);
    }

    // Construct using route.KeywordsMessage.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    public Builder clear() {
      super.clear();
      keyword_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      bitField0_ = (bitField0_ & ~0x00000001);
      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return route.SeederFactoryProto.internal_static_route_KeywordsMessage_descriptor;
    }

    public route.KeywordsMessage getDefaultInstanceForType() {
      return route.KeywordsMessage.getDefaultInstance();
    }

    public route.KeywordsMessage build() {
      route.KeywordsMessage result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public route.KeywordsMessage buildPartial() {
      route.KeywordsMessage result = new route.KeywordsMessage(this);
      int from_bitField0_ = bitField0_;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        keyword_ = keyword_.getUnmodifiableView();
        bitField0_ = (bitField0_ & ~0x00000001);
      }
      result.keyword_ = keyword_;
      onBuilt();
      return result;
    }

    public Builder clone() {
      return (Builder) super.clone();
    }
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof route.KeywordsMessage) {
        return mergeFrom((route.KeywordsMessage)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(route.KeywordsMessage other) {
      if (other == route.KeywordsMessage.getDefaultInstance()) return this;
      if (!other.keyword_.isEmpty()) {
        if (keyword_.isEmpty()) {
          keyword_ = other.keyword_;
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          ensureKeywordIsMutable();
          keyword_.addAll(other.keyword_);
        }
        onChanged();
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      route.KeywordsMessage parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (route.KeywordsMessage) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private com.google.protobuf.LazyStringList keyword_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    private void ensureKeywordIsMutable() {
      if (!((bitField0_ & 0x00000001) == 0x00000001)) {
        keyword_ = new com.google.protobuf.LazyStringArrayList(keyword_);
        bitField0_ |= 0x00000001;
       }
    }
    /**
     * <code>repeated string keyword = 1;</code>
     */
    public com.google.protobuf.ProtocolStringList
        getKeywordList() {
      return keyword_.getUnmodifiableView();
    }
    /**
     * <code>repeated string keyword = 1;</code>
     */
    public int getKeywordCount() {
      return keyword_.size();
    }
    /**
     * <code>repeated string keyword = 1;</code>
     */
    public java.lang.String getKeyword(int index) {
      return keyword_.get(index);
    }
    /**
     * <code>repeated string keyword = 1;</code>
     */
    public com.google.protobuf.ByteString
        getKeywordBytes(int index) {
      return keyword_.getByteString(index);
    }
    /**
     * <code>repeated string keyword = 1;</code>
     */
    public Builder setKeyword(
        int index, java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  ensureKeywordIsMutable();
      keyword_.set(index, value);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string keyword = 1;</code>
     */
    public Builder addKeyword(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  ensureKeywordIsMutable();
      keyword_.add(value);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string keyword = 1;</code>
     */
    public Builder addAllKeyword(
        java.lang.Iterable<java.lang.String> values) {
      ensureKeywordIsMutable();
      com.google.protobuf.AbstractMessageLite.Builder.addAll(
          values, keyword_);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string keyword = 1;</code>
     */
    public Builder clearKeyword() {
      keyword_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string keyword = 1;</code>
     */
    public Builder addKeywordBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      ensureKeywordIsMutable();
      keyword_.add(value);
      onChanged();
      return this;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:route.KeywordsMessage)
  }

  // @@protoc_insertion_point(class_scope:route.KeywordsMessage)
  private static final route.KeywordsMessage DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new route.KeywordsMessage();
  }

  public static route.KeywordsMessage getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<KeywordsMessage>
      PARSER = new com.google.protobuf.AbstractParser<KeywordsMessage>() {
    public KeywordsMessage parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
        return new KeywordsMessage(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<KeywordsMessage> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<KeywordsMessage> getParserForType() {
    return PARSER;
  }

  public route.KeywordsMessage getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

