// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/main/proto/seeder_factory.proto

package route;

public interface ListQueryOrBuilder extends
    // @@protoc_insertion_point(interface_extends:route.ListQuery)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string keywords = 1;</code>
   */
  java.lang.String getKeywords();
  /**
   * <code>string keywords = 1;</code>
   */
  com.google.protobuf.ByteString
      getKeywordsBytes();
}
