// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/main/proto/seeder_factory.proto

package route;

public interface ListQueryOrBuilder extends
    // @@protoc_insertion_point(interface_extends:route.ListQuery)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated string keyword = 1;</code>
   */
  java.util.List<java.lang.String>
      getKeywordList();
  /**
   * <code>repeated string keyword = 1;</code>
   */
  int getKeywordCount();
  /**
   * <code>repeated string keyword = 1;</code>
   */
  java.lang.String getKeyword(int index);
  /**
   * <code>repeated string keyword = 1;</code>
   */
  com.google.protobuf.ByteString
      getKeywordBytes(int index);
}
