// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/main/proto/seeder_factory.proto

package route;

/**
 * Protobuf type {@code route.Seeder}
 */
public  final class Seeder extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:route.Seeder)
    SeederOrBuilder {
private static final long serialVersionUID = 0L;
  // Use Seeder.newBuilder() to construct.
  private Seeder(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private Seeder() {
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private Seeder(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
          case 10: {
            route.Video.Builder subBuilder = null;
            if (video_ != null) {
              subBuilder = video_.toBuilder();
            }
            video_ = input.readMessage(route.Video.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(video_);
              video_ = subBuilder.buildPartial();
            }

            break;
          }
          case 18: {
            route.Endpoint.Builder subBuilder = null;
            if (endpoint_ != null) {
              subBuilder = endpoint_.toBuilder();
            }
            endpoint_ = input.readMessage(route.Endpoint.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(endpoint_);
              endpoint_ = subBuilder.buildPartial();
            }

            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return route.SeederFactoryProto.internal_static_route_Seeder_descriptor;
  }

  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return route.SeederFactoryProto.internal_static_route_Seeder_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            route.Seeder.class, route.Seeder.Builder.class);
  }

  public static final int VIDEO_FIELD_NUMBER = 1;
  private route.Video video_;
  /**
   * <code>.route.Video video = 1;</code>
   */
  public boolean hasVideo() {
    return video_ != null;
  }
  /**
   * <code>.route.Video video = 1;</code>
   */
  public route.Video getVideo() {
    return video_ == null ? route.Video.getDefaultInstance() : video_;
  }
  /**
   * <code>.route.Video video = 1;</code>
   */
  public route.VideoOrBuilder getVideoOrBuilder() {
    return getVideo();
  }

  public static final int ENDPOINT_FIELD_NUMBER = 2;
  private route.Endpoint endpoint_;
  /**
   * <code>.route.Endpoint endpoint = 2;</code>
   */
  public boolean hasEndpoint() {
    return endpoint_ != null;
  }
  /**
   * <code>.route.Endpoint endpoint = 2;</code>
   */
  public route.Endpoint getEndpoint() {
    return endpoint_ == null ? route.Endpoint.getDefaultInstance() : endpoint_;
  }
  /**
   * <code>.route.Endpoint endpoint = 2;</code>
   */
  public route.EndpointOrBuilder getEndpointOrBuilder() {
    return getEndpoint();
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (video_ != null) {
      output.writeMessage(1, getVideo());
    }
    if (endpoint_ != null) {
      output.writeMessage(2, getEndpoint());
    }
    unknownFields.writeTo(output);
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (video_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, getVideo());
    }
    if (endpoint_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, getEndpoint());
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof route.Seeder)) {
      return super.equals(obj);
    }
    route.Seeder other = (route.Seeder) obj;

    boolean result = true;
    result = result && (hasVideo() == other.hasVideo());
    if (hasVideo()) {
      result = result && getVideo()
          .equals(other.getVideo());
    }
    result = result && (hasEndpoint() == other.hasEndpoint());
    if (hasEndpoint()) {
      result = result && getEndpoint()
          .equals(other.getEndpoint());
    }
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasVideo()) {
      hash = (37 * hash) + VIDEO_FIELD_NUMBER;
      hash = (53 * hash) + getVideo().hashCode();
    }
    if (hasEndpoint()) {
      hash = (37 * hash) + ENDPOINT_FIELD_NUMBER;
      hash = (53 * hash) + getEndpoint().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static route.Seeder parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static route.Seeder parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static route.Seeder parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static route.Seeder parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static route.Seeder parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static route.Seeder parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static route.Seeder parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static route.Seeder parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static route.Seeder parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static route.Seeder parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static route.Seeder parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static route.Seeder parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(route.Seeder prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code route.Seeder}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:route.Seeder)
      route.SeederOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return route.SeederFactoryProto.internal_static_route_Seeder_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return route.SeederFactoryProto.internal_static_route_Seeder_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              route.Seeder.class, route.Seeder.Builder.class);
    }

    // Construct using route.Seeder.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    public Builder clear() {
      super.clear();
      if (videoBuilder_ == null) {
        video_ = null;
      } else {
        video_ = null;
        videoBuilder_ = null;
      }
      if (endpointBuilder_ == null) {
        endpoint_ = null;
      } else {
        endpoint_ = null;
        endpointBuilder_ = null;
      }
      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return route.SeederFactoryProto.internal_static_route_Seeder_descriptor;
    }

    public route.Seeder getDefaultInstanceForType() {
      return route.Seeder.getDefaultInstance();
    }

    public route.Seeder build() {
      route.Seeder result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public route.Seeder buildPartial() {
      route.Seeder result = new route.Seeder(this);
      if (videoBuilder_ == null) {
        result.video_ = video_;
      } else {
        result.video_ = videoBuilder_.build();
      }
      if (endpointBuilder_ == null) {
        result.endpoint_ = endpoint_;
      } else {
        result.endpoint_ = endpointBuilder_.build();
      }
      onBuilt();
      return result;
    }

    public Builder clone() {
      return (Builder) super.clone();
    }
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof route.Seeder) {
        return mergeFrom((route.Seeder)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(route.Seeder other) {
      if (other == route.Seeder.getDefaultInstance()) return this;
      if (other.hasVideo()) {
        mergeVideo(other.getVideo());
      }
      if (other.hasEndpoint()) {
        mergeEndpoint(other.getEndpoint());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      route.Seeder parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (route.Seeder) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private route.Video video_ = null;
    private com.google.protobuf.SingleFieldBuilderV3<
        route.Video, route.Video.Builder, route.VideoOrBuilder> videoBuilder_;
    /**
     * <code>.route.Video video = 1;</code>
     */
    public boolean hasVideo() {
      return videoBuilder_ != null || video_ != null;
    }
    /**
     * <code>.route.Video video = 1;</code>
     */
    public route.Video getVideo() {
      if (videoBuilder_ == null) {
        return video_ == null ? route.Video.getDefaultInstance() : video_;
      } else {
        return videoBuilder_.getMessage();
      }
    }
    /**
     * <code>.route.Video video = 1;</code>
     */
    public Builder setVideo(route.Video value) {
      if (videoBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        video_ = value;
        onChanged();
      } else {
        videoBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.route.Video video = 1;</code>
     */
    public Builder setVideo(
        route.Video.Builder builderForValue) {
      if (videoBuilder_ == null) {
        video_ = builderForValue.build();
        onChanged();
      } else {
        videoBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.route.Video video = 1;</code>
     */
    public Builder mergeVideo(route.Video value) {
      if (videoBuilder_ == null) {
        if (video_ != null) {
          video_ =
            route.Video.newBuilder(video_).mergeFrom(value).buildPartial();
        } else {
          video_ = value;
        }
        onChanged();
      } else {
        videoBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.route.Video video = 1;</code>
     */
    public Builder clearVideo() {
      if (videoBuilder_ == null) {
        video_ = null;
        onChanged();
      } else {
        video_ = null;
        videoBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.route.Video video = 1;</code>
     */
    public route.Video.Builder getVideoBuilder() {
      
      onChanged();
      return getVideoFieldBuilder().getBuilder();
    }
    /**
     * <code>.route.Video video = 1;</code>
     */
    public route.VideoOrBuilder getVideoOrBuilder() {
      if (videoBuilder_ != null) {
        return videoBuilder_.getMessageOrBuilder();
      } else {
        return video_ == null ?
            route.Video.getDefaultInstance() : video_;
      }
    }
    /**
     * <code>.route.Video video = 1;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        route.Video, route.Video.Builder, route.VideoOrBuilder> 
        getVideoFieldBuilder() {
      if (videoBuilder_ == null) {
        videoBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            route.Video, route.Video.Builder, route.VideoOrBuilder>(
                getVideo(),
                getParentForChildren(),
                isClean());
        video_ = null;
      }
      return videoBuilder_;
    }

    private route.Endpoint endpoint_ = null;
    private com.google.protobuf.SingleFieldBuilderV3<
        route.Endpoint, route.Endpoint.Builder, route.EndpointOrBuilder> endpointBuilder_;
    /**
     * <code>.route.Endpoint endpoint = 2;</code>
     */
    public boolean hasEndpoint() {
      return endpointBuilder_ != null || endpoint_ != null;
    }
    /**
     * <code>.route.Endpoint endpoint = 2;</code>
     */
    public route.Endpoint getEndpoint() {
      if (endpointBuilder_ == null) {
        return endpoint_ == null ? route.Endpoint.getDefaultInstance() : endpoint_;
      } else {
        return endpointBuilder_.getMessage();
      }
    }
    /**
     * <code>.route.Endpoint endpoint = 2;</code>
     */
    public Builder setEndpoint(route.Endpoint value) {
      if (endpointBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        endpoint_ = value;
        onChanged();
      } else {
        endpointBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.route.Endpoint endpoint = 2;</code>
     */
    public Builder setEndpoint(
        route.Endpoint.Builder builderForValue) {
      if (endpointBuilder_ == null) {
        endpoint_ = builderForValue.build();
        onChanged();
      } else {
        endpointBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.route.Endpoint endpoint = 2;</code>
     */
    public Builder mergeEndpoint(route.Endpoint value) {
      if (endpointBuilder_ == null) {
        if (endpoint_ != null) {
          endpoint_ =
            route.Endpoint.newBuilder(endpoint_).mergeFrom(value).buildPartial();
        } else {
          endpoint_ = value;
        }
        onChanged();
      } else {
        endpointBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.route.Endpoint endpoint = 2;</code>
     */
    public Builder clearEndpoint() {
      if (endpointBuilder_ == null) {
        endpoint_ = null;
        onChanged();
      } else {
        endpoint_ = null;
        endpointBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.route.Endpoint endpoint = 2;</code>
     */
    public route.Endpoint.Builder getEndpointBuilder() {
      
      onChanged();
      return getEndpointFieldBuilder().getBuilder();
    }
    /**
     * <code>.route.Endpoint endpoint = 2;</code>
     */
    public route.EndpointOrBuilder getEndpointOrBuilder() {
      if (endpointBuilder_ != null) {
        return endpointBuilder_.getMessageOrBuilder();
      } else {
        return endpoint_ == null ?
            route.Endpoint.getDefaultInstance() : endpoint_;
      }
    }
    /**
     * <code>.route.Endpoint endpoint = 2;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        route.Endpoint, route.Endpoint.Builder, route.EndpointOrBuilder> 
        getEndpointFieldBuilder() {
      if (endpointBuilder_ == null) {
        endpointBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            route.Endpoint, route.Endpoint.Builder, route.EndpointOrBuilder>(
                getEndpoint(),
                getParentForChildren(),
                isClean());
        endpoint_ = null;
      }
      return endpointBuilder_;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:route.Seeder)
  }

  // @@protoc_insertion_point(class_scope:route.Seeder)
  private static final route.Seeder DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new route.Seeder();
  }

  public static route.Seeder getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<Seeder>
      PARSER = new com.google.protobuf.AbstractParser<Seeder>() {
    public Seeder parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
        return new Seeder(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<Seeder> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<Seeder> getParserForType() {
    return PARSER;
  }

  public route.Seeder getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

