// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: seeder_factory.proto

package route;

public interface SeederOrBuilder extends
    // @@protoc_insertion_point(interface_extends:route.Seeder)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.route.Video video = 1;</code>
   */
  boolean hasVideo();
  /**
   * <code>.route.Video video = 1;</code>
   */
  route.Video getVideo();
  /**
   * <code>.route.Video video = 1;</code>
   */
  route.VideoOrBuilder getVideoOrBuilder();

  /**
   * <code>.route.Endpoint endpoint = 2;</code>
   */
  boolean hasEndpoint();
  /**
   * <code>.route.Endpoint endpoint = 2;</code>
   */
  route.Endpoint getEndpoint();
  /**
   * <code>.route.Endpoint endpoint = 2;</code>
   */
  route.EndpointOrBuilder getEndpointOrBuilder();
}
