// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/main/proto/seeder_factory.proto

package route;

public interface SeederMessageOrBuilder extends
    // @@protoc_insertion_point(interface_extends:route.SeederMessage)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.route.VideoMessage video = 1;</code>
   */
  boolean hasVideo();
  /**
   * <code>.route.VideoMessage video = 1;</code>
   */
  route.VideoMessage getVideo();
  /**
   * <code>.route.VideoMessage video = 1;</code>
   */
  route.VideoMessageOrBuilder getVideoOrBuilder();

  /**
   * <code>.route.EndpointMessage endpoint = 2;</code>
   */
  boolean hasEndpoint();
  /**
   * <code>.route.EndpointMessage endpoint = 2;</code>
   */
  route.EndpointMessage getEndpoint();
  /**
   * <code>.route.EndpointMessage endpoint = 2;</code>
   */
  route.EndpointMessageOrBuilder getEndpointOrBuilder();
}
