// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/main/proto/seeder_factory.proto

package route;

public interface SizeMessageOrBuilder extends
    // @@protoc_insertion_point(interface_extends:route.SizeMessage)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 width = 1;</code>
   */
  int getWidth();

  /**
   * <code>int32 height = 2;</code>
   */
  int getHeight();
}
