// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: seeder_factory.proto

package route;

public interface SizeOrBuilder extends
    // @@protoc_insertion_point(interface_extends:route.Size)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 width = 1;</code>
   */
  int getWidth();

  /**
   * <code>int32 height = 2;</code>
   */
  int getHeight();
}
